version: "3"

services:
  app:
    image: java-profiler-app
    build:
      context: .
    container_name: java-profiler
    restart: unless-stopped

    ports:
      - "9200:8080"

    networks:
      - prom

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M

networks:
  prom:
    external: true
    name: docker-prom_monitor-net
